<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('contents')->insert([
            [
                'title'             => 'Bienvenido al Hospital Veterinario chivo',
                'bloque_principal'  => '<p><span style="font-size:18px;"><span class="mt-3 text-center align-middle text-[18px] leading-6 tracking-normal">El primer hospital veterinario público de El Salvador</span></span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => 'Chivo Pets',
                'url'               => 'Haz tu cita',
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                // id - 2
                'title'             => 'Cuidamos con amor la salud de tu mascota',
                'bloque_principal'  => '<p style="text-align:center;"><meta charset="utf-8"><span style="color:hsl(218, 10%, 53%);"><span style="white-space:pre-wrap;">El primer hospital veterinario público de El Salvador...</span></span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => 1,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                // id - 3
                'title'             => 'Servicios médicos veterinarios',
                'bloque_principal'  => '<p><meta charset="utf-8"><span style="color:hsl(218, 10%, 53%);">Contamos con atención integral en diversas áreas...</span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => 'Ver todos los servicios',
                'type_carrusel'     => 2,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                // id - 4
                'title'             => 'Más de 3.8 millones de servicios, y aumentando',
                'bloque_principal'  => '<p style="text-align:center;"><span style="color:hsl(218, 10%, 53%);font-size:14px;">Cada atención representa una historia...</span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => 1,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                // id - 5
                'title'             => 'Satisfacción de nuestros usuarios',
                'bloque_principal'  => null,
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Cuida su salud, protege su futuro. ¡Esteriliza!',
                'bloque_principal'  => '<div class="raw-html-embed"><span class="leading-none text-white">Cuida su salud,</span> <span class="leading-none text-white ">protege su futuro.</span> <span class="leading-none text-white lg:text-[80px] md:text-[80px] sm:text-[70px]">¡Esteriliza!</span></div>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Horarios de atención',
                'bloque_principal'  => null,
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => 1,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Nuestra Ubicación',
                'bloque_principal'  => '<p><meta charset="utf-8"><span style="color:hsl(218, 10%, 53%);">Nos encontramos en Antiguo Cuscatlán...</span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => 'Abrir en Maps',
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Preguntas frecuentes (FAQ)',
                'bloque_principal'  => null,
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => 'Ver más',
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 1,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => '¿Quiénes somos?',
                'bloque_principal'  => '<p><span style="background-color:rgb(31,33,70);color:rgb(255,255,255);font-family:Inter, sans-serif;font-size:13.1px;">Hospital veterinario público, accesible e innovador; cuidamos</span></p>
                                        <p><span style="background-color:rgb(31,33,70);color:rgb(255,255,255);font-family:Inter, sans-serif;font-size:13.1px;">la salud animal y formamos profesionales en El Salvador.</span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 2,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Historia',
                'bloque_principal'  => '<p style="text-align:center;"><meta charset="utf-8"><span style="color:hsl(218, 10%, 53%);"><span style="white-space:pre-wrap;">Fundado el 26 de febrero de 2022 como parte del plan de gobierno del Presidente Nayib Bukele, el Hospital Veterinario Chivo Pets nació para cubrir la creciente demanda de un servicio veterinario integral, público y de calidad en El Salvador. En poco tiempo se convirtió en referente regional gracias a su infraestructura de vanguardia —consulta externa, emergencias 24/7, cirugía, hospitalización, imagenología, laboratorio, farmacia, rehabilitación y peluquería— y a la optimización de recursos que permite ofrecer cada consulta a un costo simbólico.</span></span><br><br><span style="color:hsl(218, 10%, 53%);"><span style="white-space:pre-wrap;">En menos de tres años hemos brindado más de 3.8 millones de atenciones y promediado 450 000 servicios por trimestre, cifras que evidencian la confianza de la población y el impacto social del proyecto. Chivo Pets integra el modelo Una Salud, que vincula bienestar animal, humano y ambiental, y funciona como hospital‑escuela: pasantes y profesionales adquieren experiencia práctica en un entorno de alta demanda, potenciando la investigación y la formación especializada en la región. Así, no solo transformamos la salud de las mascotas y sus familias, sino que también impulsamos el desarrollo de una nueva generación de veterinarios salvadoreños.</span></span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 2,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Acerca de nosotros',
                'bloque_principal'  => null,
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 2,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Áreas de servicio',
                'bloque_principal'  => '<p><span style="color:hsl(218, 10%, 53%);">Nuestro equipo se organiza en ocho áreas: Consulta Externa, Emergencia, Cirugía, Hospitalización, Imagenología, Laboratorio Clínico, Farmacia y Rehabilitación.</span></p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 2,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Convenios y alianzas',
                'bloque_principal'  => '<p class="mt-6 text-base leading-relaxed text-[#7A8393]">Mantenemos convenios con instituciones como la Universidad de El Salvador, la Universidad Salvadoreña Alberto Masferrer, el Instituto Especializado Hospital El Salvador, CLAFEM S.A. y VATUC S.A.S., entre otros.</p><p class="mt-4 text-base leading-relaxed text-[#7A8393]">Estos acuerdos impulsan la investigación, el intercambio académico y las certificaciones internacionales, fortaleciendo tanto la formación de nuestros estudiantes como la calidad de la atención veterinaria.</p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 2,
                'id_section'        => 2,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => '¿Qué hacemos en Chivo Pets?',
                'bloque_principal'  => null,
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 3,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Nuestra huella en cifras',
                'bloque_principal'  => '<p style="text-align:center;">Visualiza nuestras estadísticas de atención. Este tablero interactivo muestra en tiempo real cuántos servicios hemos brindado, reafirmando nuestro compromiso con la salud animal y la confianza de miles de familias salvadoreñas.</p><div class="w-full -mt-50 hidden lg:block" style="-webkit-text-stroke-width:0px;background-color:rgb(240, 241, 244);border-style:solid;border-width:0px;box-sizing:border-box;color:rgb(0, 0, 0);display:block;font-family:ui-sans-serif, system-ui, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;font-size:medium;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin:-200px 0px 0px;orphans:2;padding:0px;text-align:center;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;width:992px;word-spacing:0px;">&nbsp;</div>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => 1,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 3,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Servicios médicos veterinarios',
                'bloque_principal'  => '<p>En Chivo Pets, ofrecemos una atención veterinaria integral para garantizar la salud y el bienestar de las mascotas. &nbsp; &nbsp; &nbsp; Contamos con infraestructura de última generación y un equipo de médicos veterinarios comprometidos con ofrecer el mejor cuidado a cada paciente.</p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => 'Conoce más',
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 3,
                'id_locale'            => 1,
                'published_at'      => now(),
            ],
            [
                'title'             => 'Servicios de apoyo Médico Veterinario',
                'bloque_principal'  => '<p style="text-align:center;">Complementamos la atención clínica con una gama de servicios de apoyo diseñados para fortalecer el diagnóstico, tratamiento y recuperación de nuestras mascotas.</p>',
                'bloque_secundario' => null,
                'image'             => null,
                'subtitle'          => null,
                'url'               => null,
                'type_carrusel'     => null,
                'created_by_id'     => 1,
                'updated_by_id'     => 1,
                'id_section'        => 3,
                'id_locale'            => 1,
                'published_at'      => now(),
            ]
        ]);
    }
}
