<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SubMenuTablaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('submenus')->insert([
            [
                'name' => 'Historia',
                'url' => '/Quienes/quienessomos/#historia',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 1,
                'status' => true,
            ],
            [
                'name' => 'Misión y Visión',
                'url' => '/Quienes/quienessomos/#mision_visio',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 1,
                'status' => true,
            ],
            [
                'name' => 'Áreas de servicio',
                'url' => '/Quienes/quienessomos/#servicios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 1,
                'status' => true,
            ],
            [
                'name' => 'Convenios',
                'url' => '/Quienes/quienessomos/#convenios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 1,
                'status' => true,
            ],
            // fin id menu 1
            [
                'name' => 'Estadísticas de servicio',
                'url' => '/Quehacemos/quehacemos/#huellas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 2,
                'status' => true,
            ],
            [
                'name' => 'Servicios',
                'url' => '/Quehacemos/quehacemos/#servicios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 2,
                'status' => true,
            ],
            // fin id menu 2
            [
                'name' => 'Preguntas frecuentes',
                'url' => '/Experiencia/experiencia/#preguntas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 3,
                'status' => true,
            ],
            [
                'name' => 'Guía Chivo Pets',
                'url' => '/Experiencia/experiencia/#guia_chivo',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 3,
                'status' => true,
            ],
            [
                'name' => 'Blog Chivo Pet',
                'url' => '/Blog/blog/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 3,
                'status' => true,
            ],
            [
                'name' => 'Campaña de prevención',
                'url' => '/Experiencia/experiencia/#campaña',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 3,
                'status' => false,
            ],
            // fin id menu 3
            [
                'name' => 'Estadísticas de satisfacción',
                'url' => '/Valoracion/valoracion/#estadisticas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 4,
                'status' => true,
            ],
            [
                'name' => 'Experiencias y reseñas',
                'url' => '/Valoracion/valoracion/#resenias',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 4,
                'status' => true,
            ],
            // fin id menu 4
            [
                'name' => 'Programa de pasantías',
                'url' => '/Formacion/formacion/#pasantias',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 5,
                'status' => true,
            ],
            [
                'name' => 'Pets EDUCA',
                'url' => '/Formacion/formacion/#pets',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 5,
                'status' => false,
            ],
            [
                'name' => 'Casos de estudio',
                'url' => '/Formacion/casos/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 5,
                'status' => true,
            ],
            // fin id menu 5
            [
                'name' => 'Call Center 195',
                'url' => '/Formacion/casos/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 7,
                'status' => true,
            ],
            [
                'name' => 'Programar cita',
                'url' => 'https://chivopets.sv/views/formQuotes.html',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 7,
                'status' => true,
            ],
            [
                'name' => 'Ubicación',
                'url' => 'https://www.google.com/maps/place/Chivo+Pets+%7C+Hospital+Veterinario/@13.675453,-89.252143,13z/data=!4m6!3m5!1s0x8f632fc0d17a087b:0x62c853dcf744fceb!8m2!3d13.6754534!4d-89.2521427!16s%2Fg%2F11s1053wfq?entry=ttu&g_ep=EgoyMDI1MDgxMS4wIKXMDSoASAFQAw%3D%3D',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 7,
                'status' => true,
            ],
            [
                'name' => 'Forma parte del equipo',
                'url' => 'modal',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 7,
                'status' => true,
            ],
            // fin id menu 7
            [
                'name' => 'History',
                'url' => '/Quienes/quienessomos/#historia',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 8,
                'status' => true,
            ],
            [
                'name' => 'Mission and Vision',
                'url' => '/Quienes/quienessomos/#mision_visio',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 8,
                'status' => true,
            ],
            [
                'name' => 'Areas of expertise',
                'url' => '/Quienes/quienessomos/#servicios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 8,
                'status' => true,
            ],
            [
                'name' => 'Agreements',
                'url' => '/Quienes/quienessomos/#convenios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 8,
                'status' => true,
            ],
            // fin id menu 8
            [
                'name' => 'Service statistics',
                'url' => '/Quehacemos/quehacemos/#huellas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 9,
                'status' => true,
            ],
            [
                'name' => 'Services',
                'url' => '/Quehacemos/quehacemos/#servicios',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 9,
                'status' => true,
            ],
            // fin id menu 9
            [
                'name' => 'Frequently Asked Questions (FAQs)',
                'url' => '/Experiencia/experiencia/#preguntas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 10,
                'status' => true,
            ],
            [
                'name' => 'Chivo Pets Guide',
                'url' => '/Experiencia/experiencia/#guia_chivo',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 10,
                'status' => true,
            ],
            [
                'name' => 'Chivo Pets Blog',
                'url' => '/Blog/blog/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 10,
                'status' => true,
            ],
            [
                'name' => 'Prevention Campaigns',
                'url' => '/Experiencia/experiencia/#campaña',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 10,
                'status' => false,
            ],
            // fin id menu 10
            [
                'name' => 'Satisfaction Statistics',
                'url' => '/Valoracion/valoracion/#estadisticas',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 11,
                'status' => true,
            ],
            [
                'name' => 'Experiences and reviews',
                'url' => '/Valoracion/valoracion/#resenias',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 11,
                'status' => true,
            ],
            // fin id menu 11
            [
                'name' => 'Intership program',
                'url' => '/Formacion/formacion/#pasantias',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 12,
                'status' => true,
            ],
            [
                'name' => 'Pets EDUCA',
                'url' => '/Formacion/formacion/#pets',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 12,
                'status' => false,
            ],
            [
                'name' => 'Case studies',
                'url' => '/Formacion/casos/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 12,
                'status' => true,
            ],
            // fin id menu 12
            [
                'name' => 'Call Center 195',
                'url' => '/Formacion/casos/',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 14,
                'status' => true,
            ],
            [
                'name' => 'Schedule an appointment',
                'url' => 'https://chivopets.sv/views/formQuotes.html',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 14,
                'status' => true,
            ],
            [
                'name' => 'Location',
                'url' => 'https://www.google.com/maps/place/Chivo+Pets+%7C+Hospital+Veterinario/@13.675453,-89.252143,13z/data=!4m6!3m5!1s0x8f632fc0d17a087b:0x62c853dcf744fceb!8m2!3d13.6754534!4d-89.2521427!16s%2Fg%2F11s1053wfq?entry=ttu&g_ep=EgoyMDI1MDgxMS4wIKXMDSoASAFQAw%3D%3D',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 14,
                'status' => true,
            ],
            [
                'name' => 'Be part of teh team',
                'url' => 'modal',
                'created_by_id' => 1,
                'updated_by_id' => 1,
                'id_locale' => 1,
                'id_menu' => 14,
                'status' => true,
            ],
            // fin id menu 14
        ]);
    }
}
